config/routes.rb
IshManager::Engine.routes.draw do

  ##
  ## A
  ##
  root :to => 'application#home'

  get 'analytics',      to: 'analytics#index'
  get 'analytics/test', to: 'analytics#test'

  get 'application/tinymce', to: 'application#tinymce'

  resources :appliances
  resources :appliance_tmpls

  # get 'categories', to: 'categories#index'
  post '/categories/create-email-tag', to: 'categories#create_email_tag', as: :create_email_tag
  resources :categories

  resources 'events'

  patch 'galleries/:id/update_ord', to: 'galleries#update_ordering'
  get   'galleries',                to: 'galleries#index',          defaults: { render_type: Gallery::RENDER_THUMBS }
  get   'galleries/index_titles',   to: 'galleries#index',          defaults: { render_type: Gallery::RENDER_TITLES }
  get   'galleries/index_thumbs',   to: 'galleries#index',          defaults: { render_type: Gallery::RENDER_THUMBS }
  get   'galleries/shared',         to: 'galleries#shared_with_me', defaults: { render_type: Gallery::RENDER_THUMBS }
  get   'galleries/shared_titles',  to: 'galleries#shared_with_me', defaults: { render_type: Gallery::RENDER_TITLES }, as: :galleries_shared_titles
  resources :galleries do
    post 'multiadd', :to => 'photos#j_create', :as => :multiadd
  end

  get 'image_assets', to: 'image_assets#index', as: :image_assets

  post 'invoices/send/:id', to: 'invoices#email_send', as: :send_invoice
  post 'invoices/create-monthly-for/:leadset_id', to: 'invoices#create_monthly_pdf', as: :create_monthly_invoice_for_leadset
  post 'invoices/create-pdf',    to: 'invoices#create_pdf',    as: :create_invoice_pdf
  post 'invoices/create-stripe', to: 'invoices#create_stripe', as: :create_invoice_stripe
  get  'invoices/new_pdf',       to: 'invoices#new_pdf',       as: :new_invoice_pdf
  get  'invoices/new_stripe',    to: 'invoices#new_stripe',    as: :new_invoice_stripe
  post 'invoices/:id/send-stripe', to: 'invoices#send_stripe', as: :send_invoice_stripe
  resources :invoices


  resources :iro_alerts
  get 'iro_positins/roll_prep/:id', to: 'iro_purses#roll_prep', as: :iro_roll_prep
  resources :iro_positions
  get 'iro/max_pain/:ticker/on/:date', to: 'iro_option_gets#max_pain', as: :max_pain
  resources :iro_option_gets
  patch 'iro_purses/:id/show', to: 'iro_purses#update'
  get 'iro_purses/:id/edit',   to: 'iro_purses#edit', as: :edit_iro_purse
  get 'iro_purses/:id/:kind',  to: 'iro_purses#show', as: :iro_purse, defaults: { kind: 'show' } # kind: show_gameui
  resources :iro_purses
  resources :iro_strategies
  resources :iro_watches




  scope 'gameui' do
    get 'maps/:id/map-editor', to: 'maps#map_editor', as: :location_map_editor
    resources 'maps' do
      resources 'markers'
      resources 'newsitems'
    end
    post 'maps/import', to: 'maps#import', as: :import_map
    get 'maps/:id', to: 'maps#show'
    post 'maps/:id/export', to: 'maps#export', as: :export_map

    resources 'markers'
  end


  #
  # office, below
  #

  post :email_actions, to: 'email_actions#update'
  resources :email_actions

  get 'email_attachments/:id', to: 'email_attachments#show', as: :email_attachment

  post 'email_campaigns/:id/send', to: 'email_campaigns#do_send', as: :send_email_campaign
  resources :email_campaigns

  resources :email_campaign_leads # , as: :campaign_leads

  resources :email_filters

  get 'email_messages/iframe/:id',   to: 'email_messages#show_iframe',   as: :email_message_iframe
  get 'email_messages/source/:id',   to: 'email_messages#show_source',   as: :email_message_source
  get 'email_messages/stripped/:id', to: 'email_messages#show_stripped', as: :email_message_stripped
  resources :email_messages

  # post 'email_conversations/search',          to: 'email_conversations#index', as: :search_email_convos
  post 'email_conversations',                 to: 'email_conversations#index'
  get  'email_conversations',                 to: 'email_conversations#index'
  get  'email_conversations/in/:slug',        to: 'email_conversations#index', as: :email_conversations_in
  get  'email_conversations/notin/:not_slug', to: 'email_conversations#index', as: :email_conversations_notin
  get  'email_conversations/show/:id',        to: 'email_conversations#show',  as: :email_conversation

  get 'email_contexts/summary', to: 'email_contexts#summary',                           as: :email_contexts_summary
  get  'email_contexts/for_lead/:lead_id',       to: 'email_contexts#index',            as: :email_contexts_for_lead
  get  'email_contexts/iframe_src/:id',          to: 'email_contexts#iframe_src',       as: :email_context_iframe
  get  'email_contexts/new_with_template/:template_slug', to: 'email_contexts#new'
  post 'email_contexts/send_schedule/:id',       to: 'email_contexts#send_schedule',    as: :send_schedule_email_context
  post 'email_contexts/send_immediate/:id',      to: 'email_contexts#send_immediate',   as: :send_immediate_email_context
  get  'email_contexts',                         to: 'email_contexts#index',            as: :email_contexts
  resources :email_contexts

  get    'email_templates/iframe_src/:id', to: 'email_templates#iframe_src', as: :email_template_iframe
  get    'email_templates/show/:id',       to: 'email_templates#show',       as: :email_template
  patch  'email_templates/show/:id',       to: 'email_templates#update'
  delete 'email_templates/show/:id',       to: 'email_templates#destroy'
  resources :email_templates

  resources :email_unsubscribes

  ## L
  resources :lead_actions
  resources :lead_leadsets

  get 'leads',      :to => 'leads#index'
  post 'leads/bulkop', to: 'leads#bulkop'
  post 'leads/import', to: 'leads#import', as: :leads_import
  resources :leads

  resources :leadsets

  resources :leadset_tags

  resources :lead_actions
  resources :lead_action_templates

  ## M

  resources :meetings

  ## N

  resources :newsitems

  ## O

  resources :office_actions

  ## P

  resources :photos
  resources :payments
  resources :prices
  resources :products

  resources :reports

  resources :serverhosts
  resources :scheduled_email_actions

  get 'subscriptions/new_stripe', to: 'subscriptions#new_stripe', as: :new_stripe_subscription
  get 'subscriptions/new_wco',    to: 'subscriptions#new_wco',    as: :new_wco_subscription
  resources :subscriptions

  ##
  ## U
  ##
  resources :unsubscribes

  resources :user_profiles do
    resources :newsitems
  end
  resources :user_profiles, :as => :profiles do
    # resources :newsitems
  end

  ##
  ## V
  ##
  resources :videos

  resources :wco_leadsets

end

app/controllers/ish_manager/analytics_controller.rb
class IshManager::AnalyticsController < IshManager::ApplicationController

  before_action :set_vars

  def index
    authorize! :analytics, IshManager::Ability
  end

  def test
    authorize! :analytics, IshManager::Ability

    if params[:prev_interval].present?
      if !@prev_intervals.include?( params[:prev_interval] )
        flash_alert "prev_interval not allowed"
        redirect_to action: :index
        return
      end
      prev_interval = eval( params[:prev_interval] )
      selected_date = "#{(Time.now - prev_interval ).to_date.to_s},#{Time.now.to_date.to_s}"
    else
      selected_date = "#{params[:date_from]},#{params[:date_to]}"
    end

    base_url = "https://analytics.wasya.co/index.php?force_api_session=1&module=API&format=JSON&"
    # api_url_trash = "&idDimension=1&idSite=2&period=day&date=2023-07-01,2023-09-01"
    opts = {
      "token_auth" => ANALYTICS_TOKEN,
      "filter_limit" => "-1",
      "expanded" => 1,

      # "method" => "Actions.getPageUrls",
      method: params[:method],

      "idDimension" => 1,

      # "idSite" => 2,
      idSite: params[:idSite],

      # "period" => "day",
      "period" => "range",
      # period: params[:period],

      "date" => selected_date,
    }

    cids    = []
    reports = {}
    reports[9999] = []

    puts! "#{base_url}#{opts.to_query}", 'ze query'

    inns = HTTParty.get( "#{base_url}#{opts.to_query}" )
    inns = JSON.parse( inns.body )

    if "Actions.getPageUrls" == params[:method]
      inns.each do |date, items|
        items.each do |item|

          path = item['label']
          if path[0] != '/'
            path = "/#{path}"
          end

          cid = path[/.*cid=([\d]*)/,1]&.to_i
          if cid
            cids.push cid
            reports[cid] ||= []
            reports[cid].push "#{date} :: #{path}"
          end
        end
      end
    end

    if "Live.getLastVisitsDetails" == params[:method]
      inns.each do |items|
        date = items['serverDate']
        items['actionDetails'].each do |item|
          path = item['url']

          cid = path[/.*cid=([\d]*)/,1]&.to_i
          if cid
            cids.push cid
            reports[cid] ||= []
            reports[cid].push "#{date} :: #{path}"
          else
            reports[9999].push "#{date} :: #{path}"
          end
        end
      end
    end

    cids        = cids.uniq.compact
    leads_h     = Lead.find_to_h cids
    @reports = {}

    reports.each do |k, v|
      lead_label = "[#{k}] <#{leads_h[k]&.name} #{leads_h[k]&.email}>"
      @reports[lead_label] = v
    end

    @reports = @reports.sort

  end

  ##
  ## private
  ##
  private

  def set_vars
    @methods_list = [
      "Actions.getPageUrls",
      "Live.getLastVisitsDetails",
    ]


    @prev_intervals = [
      nil,
      "1.month",
      "2.months",
      "3.months",
    ]

    @sites_list = [
      [ '2 - wasya.co', 2 ],
      [ '6 - wasyaco.com', 6 ],

      [ '3 - old pi', 3 ],
      [ '8 - pi_drup', 8 ],


      [ 'bjjc_drup', 9 ],
      [ 'bjjc_legacy', 12 ],

      [ 'demmitv', 7 ],

      [ 'ish', 5 ],


    ]
  end

end

app/controllers/ish_manager/appliance_tmpls_controller.rb
class ::IshManager::ApplianceTmplsController < IshManager::ApplicationController

  before_action :set_lists

  def create
    @appliance_tmpl = Wco::ApplianceTmpl.new params[:appliance].permit!
    authorize! :create, @appliance_tmpl

    flag = @appliance_tmpl.save
    if flag
      flash[:notice] = 'Success.'
      redirect_to action: :index
    else
      flash[:alert] = "Cannot create appliance tmplate: #{@appliance_tmpl.errors.full_messages.join(', ')}."
      redirect_to action: :index
    end
  end

  def edit
    @appliance_tmpl = Wco::ApplianceTmpl.find params[:id]
    authorize! :edit, @appliance_tmpl
  end

  def index
    authorize! :index, Wco::ApplianceTmpl
    @appliance_tmpls = Wco::ApplianceTmpl.all
  end

  def update
    @appliance_tmpl = Wco::ApplianceTmpl.find params[:id]
    authorize! :update, @appliance_tmpl
    flag = @appliance_tmpl.update params[:appliance].permit!
    if flag
      flash_notice 'success'
    else
      flash_alert "Cannot update appliance template: #{@appliance_tmpl.errors.full_messages.join(', ')}."
    end
    redirect_to action: :index
  end

  ##
  ## private
  ##
  private

  def set_lists
    super
    @new_appliance_tmpl = Wco::ApplianceTmpl.new
  end

end

app/controllers/ish_manager/appliances_controller.rb
class ::IshManager::AppliancesController < IshManager::ApplicationController

  before_action :set_lists, only: %i| edit update |

  # def create
  #   @appliance_tmpl = Wco::ApplianceTmpl.new params[:appliance].permit!
  #   authorize! :create, @appliance_tmpl
  #   flag = @appliance_tmpl.save
  #   if flag
  #     flash[:notice] = 'Success.'
  #     redirect_to action: :index
  #   else
  #     flash[:alert] = "Cannot create appliance tmplate: #{@appliance_tmpl.errors.full_messages.join(', ')}."
  #     render action: :index
  #   end
  # end


  def edit
    authorize! :edit, @appliance
  end

  def index
    authorize! :index, Wco::Appliance
    @appliances = Wco::Appliance.all
  end

  def update
    authorize! :edit, @appliance
    flag = @appliance.update_attributes( params[:appliance].permit! )
    if flag
      flash[:notice] = "Successfully updated appliance #{@appliance.name}."
      redirect_to controller: :leadsets, action: :show, id: @appliance.leadset_id
      # redirect_to request.referrer ? request.referrer : { action: :edit, id: @appliance.id }
    else
      flash[:alert] = "Cannot update appliance: #{@appliance.errors.full_messages.join(', ')}."
      render action: :edit, id: @appliance.id
    end
  end


  ##
  ## private
  ##
  private

  def set_lists
    super
    @appliance = Wco::Appliance.find params[:id]
    @these_serverhosts_list = @appliance.leadset.serverhosts.map { |i| [ i.name, i.id] }
  end

end

app/controllers/ish_manager/application_controller.rb
require 'business_time'

class IshManager::ApplicationController < ActionController::Base

  protect_from_forgery :with => :exception, :prepend => true
  before_action :set_current_ability
  before_action :set_changelog
  before_action :set_title
  before_action :set_jwt
  check_authorization
  rescue_from ::CanCan::AccessDenied, :with => :access_denied

  before_action :basic_auth
  def basic_auth
    return if Rails.env.test?
    http_basic_authenticate_or_request_with :name => BASIC_AUTH_NAME, :password => BASIC_AUTH_PASSWORD
  end

  def home
    authorize! :home, IshManager::Ability
    render 'home'
  end

  def tinymce
    authorize! :home, IshManager::Ability
    render layout: false
  end

  ##
  ## private
  ##
  private

  def access_denied exception
    store_location_for :user, request.path
    redirect_to user_signed_in? ? root_path : Rails.application.routes.url_helpers.new_user_session_path, :alert => exception.message
  end

  def current_profile
    return @current_profile if @current_profile
    if current_user&.email
      return @current_profile = Ish::UserProfile.find_by({ email: current_user.email })
    end
  end

  def encode(payload, exp = 48.hours.from_now) # @TODO: definitely change, right now I expire once in 2 days.
    payload[:exp] = exp.to_i
    JWT.encode(payload, Rails.application.secrets.secret_key_base.to_s)
  end

  def flash_alert what
    flash[:alert] ||= []
    if String == what.class
      str = what
    else
      str = "Cannot create/update #{what.class.name}: #{what.errors.full_messages.join(', ')} ."
    end
    flash[:alert] << str
  end

  def flash_notice what
    flash[:notice] ||= []
    if String == what.class
      str = what
    else
      str = "Created/updated #{what.class.name} ."
    end
    flash[:notice] << str
  end

  def my_truthy? which
    ["1", "t", "T", "true"].include?( which )
  end

  def pp_errors err
    err
  end

  def puts! a, b=''
    puts "+++ +++ #{b}"
    puts a.inspect
  end

  def set_changelog
    @version = Gem.loaded_specs['ish_manager'].version.to_s
  end

  def set_current_ability
    if !current_user
      raise ::CanCan::AccessDenied
    end
    @current_profile ||= ::Ish::UserProfile.find_by({ email: current_user.email })
    @current_ability ||= ::IshManager::Ability.new( @current_profile )
  end

  def set_jwt
    @jwt_token = encode(user_profile_id: @current_user.profile.id.to_s)
  end

  def set_lists
    @blank_template       = Tmpl.new

    @email_campaigns_list = [[nil,nil]] + Ish::EmailCampaign.all.map { |c| [ c.slug, c.id ] }
    @email_actions_list   = EAct.list
    @email_templates_list = [[nil,nil]] + Ish::EmailTemplate.all.map { |t| [ t.slug, t.id ] }
    @email_tags_list      = [[nil,nil]] + WpTag.email_tags.map { |t| [ t.name, t.id ] }
    @leads_list           = Lead.list
    @leadsets_list        = Leadset.list
    @locations_list       = ::Gameui::Map.list
    @maps_list            = ::Gameui::Map.list # @TODO: missing nonpublic!
    @office_actions_list  = [[nil,nil]] + Office::Action.all.map { |a| [ a.slug, a.id ] }
    @profiles_list        = Ish::UserProfile.list
    @reports_list         = Report.all.list
    @tags_list            = [[nil,nil]] + WpTag.all.map { |t| [ t.name, t.id ] }
    @user_profiles_list   = Ish::UserProfile.list

  end

  def set_title
    @page_title = "#{ params[:controller].gsub('ish_manager/', '') } #{params[:action]} #{params[:slug]||params[:id]} ".gsub("  ", " ")
  end

end

app/controllers/ish_manager/application_mailer_controller.rb
class IshManager::ApplicationMailerController < ActionController::Base
  helper IshManager::ApplicationHelper

  def url_options
    {
      host: 'test-host',
    }
  end
end

app/controllers/ish_manager/categories_controller.rb
class ::IshManager::CategoriesController < IshManager::ApplicationController

  before_action :set_lists

  def index
    authorize! :categories_index, IshManager::Ability
    # @categories = Category.all_hierarchical
    @categories_flat = Category.all_flat
    @tags = Category.all_tags
  end

  def show
    @category = WpTag.find params[:id]
    authorize! :show, @category

    ## same as in leads#index
    @leads = @category.leads
    if params[:q].present?
      @leads = @leads.where(" email LIKE ? ", "%#{params[:q]}%" )
    end
    @leads = @leads.page( params[:leads_page] ).per( current_profile.per_page )
  end

  def create_email_tag
    @tag = WpTag.emailtag( params[:tag][:name] )
    authorize! :create, @tag
    @tag.persisted? ? flash_notice('persisted') : flash_alert('cannot save tag')
    redirect_to request.referrer ? request.referrer : email_conversations_path
  end

end

app/controllers/ish_manager/email_attachments_controller.rb
class ::IshManager::EmailAttachmentsController < IshManager::ApplicationController

  def show
    att = Office::EmailAttachment.find params[:id]
    authorize! :show, att
    send_data(
      att.content,
      filename: att.filename || "this_download",
      type: att.content_type )
  end

end

app/controllers/ish_manager/image_assets_controller.rb
##
## trash?! _vp_ 2023-05-10
##
class IshManager::ImageAssetsController < IshManager::ApplicationController

  def index
    authorize! :index, Ish::ImageAsset
    @image_assets = Ish::ImageAsset.all.order_by( created_at: :desc )
  end

end

app/views/ish_manager/leads/_form.haml
- url = lead.new_record? ? leads_path : lead_path( lead.id )

= form_for lead, html: { multipart: true }, as: :lead, url: url do |f|

  .field
    = f.label :name
    = f.text_field :name

  .field
    = f.label :email
    = f.text_field :email

  .field
    = f.label :phone
    = f.text_field :phone

  .field
    = f.label :address
    = f.text_field :address

  .field
    = f.label "Leadset (company)"
    = f.select :m3_leadset_id, options_for_select(@leadsets_list, selected: lead.m3_leadset_id), { include_blank: true }, { class: :select2 }

  .field
    %label Rating
    = f.number_field :rating

  .field
    = f.label :comment
    = f.text_area :comment, class: :tinymce

  .field
    = f.label "Tags"
    = lead.wp_tags.inspect
    = f.select :lead_tags, options_for_select(@tags_list, selected: lead.wp_tags.map(&:term_id) ), {}, { class: :select2, multiple: true }

  .field
    = f.label :photo
    = f.file_field :photo

  .actions
    = f.submit

app/views/ish_manager/leads/_form_import.haml
.Card
  = form_tag leads_import_path, multipart: true do
    .doc
      %pre= Lead.import_v1_fields
    .field
      %label File
      = file_field_tag :csv_file

    .actions
      = submit_tag 'Submit'

app/views/ish_manager/leads/_index.haml
-#
-# receives locals: leads , search_path
-#
-# - email_contexts ||= {}

.leads--index.padded
  .header
    %h2.title
      Leads
      - if !defined?( skip_pagination ) || !skip_pagination
        (#{leads.total_count})
      - else
        (#{leads.length})
      = link_to raw("<i class='fa fa-plus-square'></i>"), new_lead_path

  - if defined?( search_path )
    .float-right= render 'search', path: search_path
  = form_tag leads_bulkop_path do
    = label_tag 'Act on Selected:'
    = select_tag :op, options_for_select( [[nil,nil]] + Lead::OPS )
    = select_tag :email_campaign_id, options_for_select( @email_campaigns_list )
    = submit_tag 'Go'

    - if !defined?( skip_pagination ) || !skip_pagination
      = paginate leads, param_name: :leads_page
    %table.bordered
      %thead
        %tr
          %th= check_box_tag :selectAll
          %th Name/Email
          %th
          %th.company Company
          %th Phone, address
          %th Tag
          %th created_at
          %th.ctxs Ctxs
          %th Sch

      %tbody
        - leads.each do |lead|
          %tr
            %td= check_box_tag 'lead_ids[]', lead.id
            %td
              = link_to '[~]', edit_lead_path( lead )
              = link_to "#{lead.name} <#{lead.email}>", lead_path( lead )
            %td
              = image_tag lead.photo.url(:thumb) if lead.photo
            %td.company
              = lead.company.company_url
              - if lead.company.name.present?
                <br /><b>#{lead.company.name}</b>
            %td
              .a= lead.phone   if lead.phone.present?
              .a= lead.address if lead.address.present?
            %td= lead.wp_tags.map(&:name).join(", ")
            %td= lead.created_at.to_s[0..10]
            %td.ctxs
              = lead.email_contexts.length
              -## without the N+1 but unfinished and messy:
              -# = email_contexts[lead.id] || '-'

            %td.sch
              = lead.scheduled_email_actions.length
              = link_to '[+]', new_scheduled_email_action_path( lead_id: lead.id )
              -# %ul
              -#   - lead.scheduled_email_actions.map do |sch_a|
              -#     %li
              -#       = link_to sch_a.email_action.slug, edit_scheduled_email_action_path( sch_a )
              -#       [x]

    - if !defined?( skip_pagination ) || !skip_pagination
      = paginate leads, param_name: :leads_page

app/views/ish_manager/leads/_index_rows.haml
.leads--index-rows
  - leads.each do |lead|
    .item
      = link_to lead.email, lead_path(lead)
      \(#{lead.scheduled_email_actions.length} sch
      %span.expand-next [+]
      .expand-hide= render 'ish_manager/scheduled_actions/form_mini'
      \)
      %span.expand-next [reply]
      .expand-hide= render 'ish_manager/email_contexts/form_reply', lead: lead

app/views/ish_manager/leads/edit.haml
.leads-edit.max-width
  .header
    %h2.title Edit lead #{ link_to @lead.name, lead_path(@lead) }

  = render 'form', :lead => @lead

  -# %hr
  -# %h1 Email Campaigns:
  -# %ul
  -#   - @lead.email_campaign_leads.each do |x|
  -#     %li
  -#       <b>Sent on ::</b> #{x.sent_at.to_s[0..10]}
  -#       <b>Slug ::</b> #{x.email_campaign.slug}

  -# %hr
  -# %h1 Single Emails:
  -# %ul
  -#   - @lead.email_contexts.each do |x|
  -#     %li
  -#       <b>Sent at ::</b> #{x.sent_at.to_s[0..10]}
  -#       <b>Subject ::</b> #{x.subject}

app/views/ish_manager/leads/index.haml
.leads-index.max-width
  = form_tag leads_path, method: :get do
    = select_tag :q_tag_ids, options_for_select(@tags_list, selected: params[:q_tag_ids]), { class: :select2, multiple: true }
    = submit_tag 'tag-search'
  %hr
  = render 'index', leads: @leads, search_path: leads_path

app/views/ish_manager/leads/new.haml
.leads-new.max-width
  .row
    .col-sm-12.col-md-6
      %h1 New Lead
      = render 'form', lead: @lead
    .col-sm-12.col-md-6
      %h1 Import Leads
      = render 'form_import'

app/views/ish_manager/leads/show.haml
.leads-show.padded

  .header
    %h2.title
      Lead ##{@lead.id}
      = link_to '[~]', edit_lead_path(@lead)

  .row
    .col-md-6
      %ul
        %li Name: #{@lead.name}
        %li Email: #{@lead.email}
        %li
          Company (leadset): #{ link_to @lead.company.company_url, leadset_path(@lead.company) }
          (#{@lead.m3_leadset_id})
        %li Rating: #{@lead.rating}
        - if @lead.phone
          %li Phone: #{@lead.phone}
        - if @lead.address
          %li Address: #{@lead.address}
        - if @lead.shoe_size
          %li Shoe size: #{@lead.shoe_size}
        - if @lead.comment
          %li Comment: #{raw @lead.comment}
        - if @lead.photo
          %li
            = image_tag Photo.find( @lead.photo_id ).photo.url(:small)

    .col-md-6
      %h5 Tags
      %ul
        - @lead.lead_tags.each do |lt|
          %li
            = link_to category_path(lt.wp_tag.id) do
              = "##{lt.wp_tag.id} - #{lt.wp_tag.name}"

  .row
    .col-md-6.ctxs
      %h5
        Email Contexts (#{@ctxs.length})
        = link_to '[+]', '#'
      %ul
        - @ctxs.each do |ctx|
          %li
            = pp_date( ctx.sent_at ) || 'not sent'
            = link_to ctx.subject.presence||"No Subj?!", email_context_path(ctx)

    .col-md-6.schs
      %h5
        Scheduled actions (#{@schs.length})
        -# = link_to '[+]', '#'
        \[+]
      %ul
        - @schs.each do |sch|
          %li
            = link_to sch.email_action.slug, edit_scheduled_email_action_path(sch)
            = sch.state
            (#{link_to 'proto-action', edit_email_action_path(sch.email_action)})
            = sch.perform_at

      %hr
      %h5
        Invoices (?)
        = link_to '[+stripe]', new_invoice_stripe_path({ leadset_id: @lead.m3_leadset_id })
        = link_to '[+pdf]', new_invoice_pdf_path({ leadset_id: @lead.m3_leadset_id })
      %ul
        %li None?



  .row
    .col-md-12.msgs
      %h5 Email Conversations (#{@convs.length})
      %ul
        - @convs.each do |conv|
          %li
            = link_to conv.subject, email_conversation_path( conv )

  .row
    .col-md-6
      = render 'ish_manager/galleries/index', galleries: @galleries
    .col-md-6
      = render 'ish_manager/videos/index', videos: @videos