config/routes.rb
IshManager::Engine.routes.draw do

  ##
  ## A
  ##
  root :to => 'application#home'

  get 'analytics',      to: 'analytics#index'
  get 'analytics/test', to: 'analytics#test'

  get 'application/tinymce', to: 'application#tinymce'

  resources :appliances
  resources :appliance_tmpls

  # get 'categories', to: 'categories#index'
  post '/categories/create-email-tag', to: 'categories#create_email_tag', as: :create_email_tag
  resources :categories

  resources 'events'

  patch 'galleries/:id/update_ord', to: 'galleries#update_ordering'
  get   'galleries',                to: 'galleries#index',          defaults: { render_type: Gallery::RENDER_THUMBS }
  get   'galleries/index_titles',   to: 'galleries#index',          defaults: { render_type: Gallery::RENDER_TITLES }
  get   'galleries/index_thumbs',   to: 'galleries#index',          defaults: { render_type: Gallery::RENDER_THUMBS }
  get   'galleries/shared',         to: 'galleries#shared_with_me', defaults: { render_type: Gallery::RENDER_THUMBS }
  get   'galleries/shared_titles',  to: 'galleries#shared_with_me', defaults: { render_type: Gallery::RENDER_TITLES }, as: :galleries_shared_titles
  resources :galleries do
    post 'multiadd', :to => 'photos#j_create', :as => :multiadd
  end

  get 'image_assets', to: 'image_assets#index', as: :image_assets

  post 'invoices/send/:id', to: 'invoices#email_send', as: :send_invoice
  post 'invoices/create-monthly-for/:leadset_id', to: 'invoices#create_monthly_pdf', as: :create_monthly_invoice_for_leadset
  post 'invoices/create-pdf',    to: 'invoices#create_pdf',    as: :create_invoice_pdf
  post 'invoices/create-stripe', to: 'invoices#create_stripe', as: :create_invoice_stripe
  get  'invoices/new_pdf',       to: 'invoices#new_pdf',       as: :new_invoice_pdf
  get  'invoices/new_stripe',    to: 'invoices#new_stripe',    as: :new_invoice_stripe
  post 'invoices/:id/send-stripe', to: 'invoices#send_stripe', as: :send_invoice_stripe
  resources :invoices


  resources :iro_alerts
  get 'iro_positins/roll_prep/:id', to: 'iro_purses#roll_prep', as: :iro_roll_prep
  resources :iro_positions
  get 'iro/max_pain/:ticker/on/:date', to: 'iro_option_gets#max_pain', as: :max_pain
  resources :iro_option_gets
  patch 'iro_purses/:id/show', to: 'iro_purses#update'
  get 'iro_purses/:id/edit',   to: 'iro_purses#edit', as: :edit_iro_purse
  get 'iro_purses/:id/:kind',  to: 'iro_purses#show', as: :iro_purse, defaults: { kind: 'show' } # kind: show_gameui
  resources :iro_purses
  resources :iro_strategies
  resources :iro_watches




  scope 'gameui' do
    get 'maps/:id/map-editor', to: 'maps#map_editor', as: :location_map_editor
    resources 'maps' do
      resources 'markers'
      resources 'newsitems'
    end
    post 'maps/import', to: 'maps#import', as: :import_map
    get 'maps/:id', to: 'maps#show'
    post 'maps/:id/export', to: 'maps#export', as: :export_map

    resources 'markers'
  end


  #
  # office, below
  #

  post :email_actions, to: 'email_actions#update'
  resources :email_actions

  get 'email_attachments/:id', to: 'email_attachments#show', as: :email_attachment

  post 'email_campaigns/:id/send', to: 'email_campaigns#do_send', as: :send_email_campaign
  resources :email_campaigns

  resources :email_campaign_leads # , as: :campaign_leads

  resources :email_filters

  get 'email_messages/iframe/:id',   to: 'email_messages#show_iframe',   as: :email_message_iframe
  get 'email_messages/source/:id',   to: 'email_messages#show_source',   as: :email_message_source
  get 'email_messages/stripped/:id', to: 'email_messages#show_stripped', as: :email_message_stripped
  resources :email_messages

  # post 'email_conversations/search',          to: 'email_conversations#index', as: :search_email_convos
  post 'email_conversations',                 to: 'email_conversations#index'
  get  'email_conversations',                 to: 'email_conversations#index'
  get  'email_conversations/in/:slug',        to: 'email_conversations#index', as: :email_conversations_in
  get  'email_conversations/notin/:not_slug', to: 'email_conversations#index', as: :email_conversations_notin
  get  'email_conversations/show/:id',        to: 'email_conversations#show',  as: :email_conversation

  get 'email_contexts/summary', to: 'email_contexts#summary',                           as: :email_contexts_summary
  get  'email_contexts/for_lead/:lead_id',       to: 'email_contexts#index',            as: :email_contexts_for_lead
  get  'email_contexts/iframe_src/:id',          to: 'email_contexts#iframe_src',       as: :email_context_iframe
  get  'email_contexts/new_with_template/:template_slug', to: 'email_contexts#new'
  post 'email_contexts/send_schedule/:id',       to: 'email_contexts#send_schedule',    as: :send_schedule_email_context
  post 'email_contexts/send_immediate/:id',      to: 'email_contexts#send_immediate',   as: :send_immediate_email_context
  get  'email_contexts',                         to: 'email_contexts#index',            as: :email_contexts
  resources :email_contexts

  get    'email_templates/iframe_src/:id', to: 'email_templates#iframe_src', as: :email_template_iframe
  get    'email_templates/show/:id',       to: 'email_templates#show',       as: :email_template
  patch  'email_templates/show/:id',       to: 'email_templates#update'
  delete 'email_templates/show/:id',       to: 'email_templates#destroy'
  resources :email_templates

  resources :email_unsubscribes

  ## L
  resources :lead_actions
  resources :lead_leadsets

  get 'leads',      :to => 'leads#index'
  post 'leads/bulkop', to: 'leads#bulkop'
  post 'leads/import', to: 'leads#import', as: :leads_import
  resources :leads

  resources :leadsets

  resources :leadset_tags

  resources :lead_actions
  resources :lead_action_templates

  ## M

  resources :meetings

  ## N

  resources :newsitems

  ## O

  resources :office_actions

  ## P

  resources :photos
  resources :payments
  resources :prices
  resources :products

  resources :reports

  resources :serverhosts
  resources :scheduled_email_actions

  get 'subscriptions/new_stripe', to: 'subscriptions#new_stripe', as: :new_stripe_subscription
  get 'subscriptions/new_wco',    to: 'subscriptions#new_wco',    as: :new_wco_subscription
  resources :subscriptions

  ##
  ## U
  ##
  resources :unsubscribes

  resources :user_profiles do
    resources :newsitems
  end
  resources :user_profiles, :as => :profiles do
    # resources :newsitems
  end

  ##
  ## V
  ##
  resources :videos

  resources :wco_leadsets

end

app/controllers/ish_manager/analytics_controller.rb
class IshManager::AnalyticsController < IshManager::ApplicationController

  before_action :set_vars

  def index
    authorize! :analytics, IshManager::Ability
  end

  def test
    authorize! :analytics, IshManager::Ability

    if params[:prev_interval].present?
      if !@prev_intervals.include?( params[:prev_interval] )
        flash_alert "prev_interval not allowed"
        redirect_to action: :index
        return
      end
      prev_interval = eval( params[:prev_interval] )
      selected_date = "#{(Time.now - prev_interval ).to_date.to_s},#{Time.now.to_date.to_s}"
    else
      selected_date = "#{params[:date_from]},#{params[:date_to]}"
    end

    base_url = "https://analytics.wasya.co/index.php?force_api_session=1&module=API&format=JSON&"
    # api_url_trash = "&idDimension=1&idSite=2&period=day&date=2023-07-01,2023-09-01"
    opts = {
      "token_auth" => ANALYTICS_TOKEN,
      "filter_limit" => "-1",
      "expanded" => 1,

      # "method" => "Actions.getPageUrls",
      method: params[:method],

      "idDimension" => 1,

      # "idSite" => 2,
      idSite: params[:idSite],

      # "period" => "day",
      "period" => "range",
      # period: params[:period],

      "date" => selected_date,
    }

    cids    = []
    reports = {}
    reports[9999] = []

    puts! "#{base_url}#{opts.to_query}", 'ze query'

    inns = HTTParty.get( "#{base_url}#{opts.to_query}" )
    inns = JSON.parse( inns.body )

    if "Actions.getPageUrls" == params[:method]
      inns.each do |date, items|
        items.each do |item|

          path = item['label']
          if path[0] != '/'
            path = "/#{path}"
          end

          cid = path[/.*cid=([\d]*)/,1]&.to_i
          if cid
            cids.push cid
            reports[cid] ||= []
            reports[cid].push "#{date} :: #{path}"
          end
        end
      end
    end

    if "Live.getLastVisitsDetails" == params[:method]
      inns.each do |items|
        date = items['serverDate']
        items['actionDetails'].each do |item|
          path = item['url']

          cid = path[/.*cid=([\d]*)/,1]&.to_i
          if cid
            cids.push cid
            reports[cid] ||= []
            reports[cid].push "#{date} :: #{path}"
          else
            reports[9999].push "#{date} :: #{path}"
          end
        end
      end
    end

    cids        = cids.uniq.compact
    leads_h     = Lead.find_to_h cids
    @reports = {}

    reports.each do |k, v|
      lead_label = "[#{k}] <#{leads_h[k]&.name} #{leads_h[k]&.email}>"
      @reports[lead_label] = v
    end

    @reports = @reports.sort

  end

  ##
  ## private
  ##
  private

  def set_vars
    @methods_list = [
      "Actions.getPageUrls",
      "Live.getLastVisitsDetails",
    ]


    @prev_intervals = [
      nil,
      "1.month",
      "2.months",
      "3.months",
    ]

    @sites_list = [
      [ '2 - wasya.co', 2 ],
      [ '6 - wasyaco.com', 6 ],

      [ '3 - old pi', 3 ],
      [ '8 - pi_drup', 8 ],


      [ 'bjjc_drup', 9 ],
      [ 'bjjc_legacy', 12 ],

      [ 'demmitv', 7 ],

      [ 'ish', 5 ],


    ]
  end

end

app/controllers/ish_manager/appliance_tmpls_controller.rb
class ::IshManager::ApplianceTmplsController < IshManager::ApplicationController

  before_action :set_lists

  def create
    @appliance_tmpl = Wco::ApplianceTmpl.new params[:appliance].permit!
    authorize! :create, @appliance_tmpl

    flag = @appliance_tmpl.save
    if flag
      flash[:notice] = 'Success.'
      redirect_to action: :index
    else
      flash[:alert] = "Cannot create appliance tmplate: #{@appliance_tmpl.errors.full_messages.join(', ')}."
      redirect_to action: :index
    end
  end

  def edit
    @appliance_tmpl = Wco::ApplianceTmpl.find params[:id]
    authorize! :edit, @appliance_tmpl
  end

  def index
    authorize! :index, Wco::ApplianceTmpl
    @appliance_tmpls = Wco::ApplianceTmpl.all
  end

  def update
    @appliance_tmpl = Wco::ApplianceTmpl.find params[:id]
    authorize! :update, @appliance_tmpl
    flag = @appliance_tmpl.update params[:appliance].permit!
    if flag
      flash_notice 'success'
    else
      flash_alert "Cannot update appliance template: #{@appliance_tmpl.errors.full_messages.join(', ')}."
    end
    redirect_to action: :index
  end

  ##
  ## private
  ##
  private

  def set_lists
    super
    @new_appliance_tmpl = Wco::ApplianceTmpl.new
  end

end

app/controllers/ish_manager/appliances_controller.rb
class ::IshManager::AppliancesController < IshManager::ApplicationController

  before_action :set_lists, only: %i| edit update |

  # def create
  #   @appliance_tmpl = Wco::ApplianceTmpl.new params[:appliance].permit!
  #   authorize! :create, @appliance_tmpl
  #   flag = @appliance_tmpl.save
  #   if flag
  #     flash[:notice] = 'Success.'
  #     redirect_to action: :index
  #   else
  #     flash[:alert] = "Cannot create appliance tmplate: #{@appliance_tmpl.errors.full_messages.join(', ')}."
  #     render action: :index
  #   end
  # end


  def edit
    authorize! :edit, @appliance
  end

  def index
    authorize! :index, Wco::Appliance
    @appliances = Wco::Appliance.all
  end

  def update
    authorize! :edit, @appliance
    flag = @appliance.update_attributes( params[:appliance].permit! )
    if flag
      flash[:notice] = "Successfully updated appliance #{@appliance.name}."
      redirect_to controller: :leadsets, action: :show, id: @appliance.leadset_id
      # redirect_to request.referrer ? request.referrer : { action: :edit, id: @appliance.id }
    else
      flash[:alert] = "Cannot update appliance: #{@appliance.errors.full_messages.join(', ')}."
      render action: :edit, id: @appliance.id
    end
  end


  ##
  ## private
  ##
  private

  def set_lists
    super
    @appliance = Wco::Appliance.find params[:id]
    @these_serverhosts_list = @appliance.leadset.serverhosts.map { |i| [ i.name, i.id] }
  end

end

app/controllers/ish_manager/application_controller.rb
require 'business_time'

class IshManager::ApplicationController < ActionController::Base

  protect_from_forgery :with => :exception, :prepend => true
  before_action :set_current_ability
  before_action :set_changelog
  before_action :set_title
  before_action :set_jwt
  check_authorization
  rescue_from ::CanCan::AccessDenied, :with => :access_denied

  before_action :basic_auth
  def basic_auth
    return if Rails.env.test?
    http_basic_authenticate_or_request_with :name => BASIC_AUTH_NAME, :password => BASIC_AUTH_PASSWORD
  end

  def home
    authorize! :home, IshManager::Ability
    render 'home'
  end

  def tinymce
    authorize! :home, IshManager::Ability
    render layout: false
  end

  ##
  ## private
  ##
  private

  def access_denied exception
    store_location_for :user, request.path
    redirect_to user_signed_in? ? root_path : Rails.application.routes.url_helpers.new_user_session_path, :alert => exception.message
  end

  def current_profile
    return @current_profile if @current_profile
    if current_user&.email
      return @current_profile = Ish::UserProfile.find_by({ email: current_user.email })
    end
  end

  def encode(payload, exp = 48.hours.from_now) # @TODO: definitely change, right now I expire once in 2 days.
    payload[:exp] = exp.to_i
    JWT.encode(payload, Rails.application.secrets.secret_key_base.to_s)
  end

  def flash_alert what
    flash[:alert] ||= []
    if String == what.class
      str = what
    else
      str = "Cannot create/update #{what.class.name}: #{what.errors.full_messages.join(', ')} ."
    end
    flash[:alert] << str
  end

  def flash_notice what
    flash[:notice] ||= []
    if String == what.class
      str = what
    else
      str = "Created/updated #{what.class.name} ."
    end
    flash[:notice] << str
  end

  def my_truthy? which
    ["1", "t", "T", "true"].include?( which )
  end

  def pp_errors err
    err
  end

  def puts! a, b=''
    puts "+++ +++ #{b}"
    puts a.inspect
  end

  def set_changelog
    @version = Gem.loaded_specs['ish_manager'].version.to_s
  end

  def set_current_ability
    if !current_user
      raise ::CanCan::AccessDenied
    end
    @current_profile ||= ::Ish::UserProfile.find_by({ email: current_user.email })
    @current_ability ||= ::IshManager::Ability.new( @current_profile )
  end

  def set_jwt
    @jwt_token = encode(user_profile_id: @current_user.profile.id.to_s)
  end

  def set_lists
    @blank_template       = Tmpl.new

    @email_campaigns_list = [[nil,nil]] + Ish::EmailCampaign.all.map { |c| [ c.slug, c.id ] }
    @email_actions_list   = EAct.list
    @email_templates_list = [[nil,nil]] + Ish::EmailTemplate.all.map { |t| [ t.slug, t.id ] }
    @email_tags_list      = [[nil,nil]] + WpTag.email_tags.map { |t| [ t.name, t.id ] }
    @leads_list           = Lead.list
    @leadsets_list        = Leadset.list
    @locations_list       = ::Gameui::Map.list
    @maps_list            = ::Gameui::Map.list # @TODO: missing nonpublic!
    @office_actions_list  = [[nil,nil]] + Office::Action.all.map { |a| [ a.slug, a.id ] }
    @profiles_list        = Ish::UserProfile.list
    @reports_list         = Report.all.list
    @tags_list            = [[nil,nil]] + WpTag.all.map { |t| [ t.name, t.id ] }
    @user_profiles_list   = Ish::UserProfile.list

  end

  def set_title
    @page_title = "#{ params[:controller].gsub('ish_manager/', '') } #{params[:action]} #{params[:slug]||params[:id]} ".gsub("  ", " ")
  end

end

app/controllers/ish_manager/application_mailer_controller.rb
class IshManager::ApplicationMailerController < ActionController::Base
  helper IshManager::ApplicationHelper

  def url_options
    {
      host: 'test-host',
    }
  end
end

app/controllers/ish_manager/categories_controller.rb
class ::IshManager::CategoriesController < IshManager::ApplicationController

  before_action :set_lists

  def index
    authorize! :categories_index, IshManager::Ability
    # @categories = Category.all_hierarchical
    @categories_flat = Category.all_flat
    @tags = Category.all_tags
  end

  def show
    @category = WpTag.find params[:id]
    authorize! :show, @category

    ## same as in leads#index
    @leads = @category.leads
    if params[:q].present?
      @leads = @leads.where(" email LIKE ? ", "%#{params[:q]}%" )
    end
    @leads = @leads.page( params[:leads_page] ).per( current_profile.per_page )
  end

  def create_email_tag
    @tag = WpTag.emailtag( params[:tag][:name] )
    authorize! :create, @tag
    @tag.persisted? ? flash_notice('persisted') : flash_alert('cannot save tag')
    redirect_to request.referrer ? request.referrer : email_conversations_path
  end

end

app/controllers/ish_manager/email_attachments_controller.rb
class ::IshManager::EmailAttachmentsController < IshManager::ApplicationController

  def show
    att = Office::EmailAttachment.find params[:id]
    authorize! :show, att
    send_data(
      att.content,
      filename: att.filename || "this_download",
      type: att.content_type )
  end

end

app/controllers/ish_manager/image_assets_controller.rb
##
## trash?! _vp_ 2023-05-10
##
class IshManager::ImageAssetsController < IshManager::ApplicationController

  def index
    authorize! :index, Ish::ImageAsset
    @image_assets = Ish::ImageAsset.all.order_by( created_at: :desc )
  end

end

app/views/ish_manager/newsitems/_form.haml
-#
-# ish_manager / newsitems / _form
-#

= form_for newsitem, :html => { :multipart => true } do |f|
  .row
    .col-sm-6
      .field
        = f.label :map
        = f.select :map_id, options_for_select( @maps_list, selected:( newsitem[:map_id] || params[:map_id] ) ), {}, class: 'select2'
      .field
        = f.label :profile
        = f.select :profile_id, options_for_select( @profiles_list, selected: newsitem[:profile_id] ), {}, class: 'select2'
    .col-sm-6
      = f.submit :submit

  %hr
  .row
    .col-sm-6
      .field
        = f.label :name
        = f.text_field :name
      .field
        = label_tag :photo
        = file_field_tag :photo
      .field
        = f.label :subhead
        = f.text_area :subhead
      .field
        = f.label :descr
        = f.text_area :descr
        .descr= raw newsitem.descr
      .field
        = f.label :iframe_src
        = f.text_field :iframe_src

    .col-sm-6
      .field
        = f.label :video
        = f.select :video_id, options_for_select( @videos_list, :selected => @newsitem.video_id ), {}, class: 'select2'
      .field
        = f.label :gallery
        = f.select :gallery_id, options_for_select( @galleries_list, :selected => @newsitem.gallery_id ), {}, class: 'select2'
      .field
        = f.label :report
        = f.select :report_id, options_for_select( @reports_list, :selected => @newsitem.report_id ), {}, class: 'select2'

app/views/ish_manager/newsitems/_header.haml
-# %h5 Newsitems (#{newsitems.count}) #{link_to image_new, new_newsitem_path }
Newsitems (#{newsitems.count}) #{link_to image_new, new_newsitem_path }

app/views/ish_manager/newsitems/_index.haml
-#
-# ish_manager / newsitems / _index
-#

- newsitems = newsitems.page( params[:newsitems_page] ).per( 10 )


.manager-newsitems--index
  = paginate newsitems, :param_name => :newsitems_page, :views_prefix => 'ish_manager'
  - newsitems.each do |n|
    = render 'ish_manager/newsitems/item', :newsitem => n

  = paginate newsitems, :param_name => :newsitems_page, :views_prefix => 'ish_manager'

app/views/ish_manager/newsitems/_item.haml
-#
-# ish_manager / newsitems / _item.haml
-#

- n ||= newsitem

.card.newsitems--item{ class: n.item_type }
  .card-content
    .float-left= link_to '[~]', edit_newsitem_path(n)
    .float-left= button_to '[x]', newsitem_path( n ), :method => :delete, :data => { :confirm => 'Are you sure?' }

    - if !n.photo.blank?
      .the-photo
        - if n.photo.gallery.blank?
          = link_to image_tag( n.photo.photo.url(:small) ), n.photo.photo.url(:large), :rel => 'lightbox[newsitem]'
        - else
          = link_to image_tag( n.photo.photo.url(:small) ), gallery_path( n.photo.gallery.slug, n.photo.gallery.photos.index(n.photo) )
      .meta= render 'ish_manager/photos/meta', :photo => n.photo

    - if n.report
      %ul
        %li <b>Report</b> #{n.report.id}
        %li Premium Tier #{n.report.premium_tier}
      %h5
        = link_to n.report.name, report_path(n.report.slug)
        = link_to "[~]", edit_report_path(n.report)
      .meta
        on #{pretty_date n.report.created_at} by #{n.report.user_profile&.name || '<anonymous>'}
      - unless n.report.photo.blank?
        .thumb= link_to image_tag(n.report.photo.photo.url(:thumb), :alt => ''), report_path( n.report.slug )
      .subhead= n.report.subhead
      .c

    - if !n.gallery.blank?
      %h3= link_to n.gallery.name, gallery_path(n.gallery.slug, 0)
      .meta
        #{t('newsitems.gallery', :username => n.gallery.username, :date => pretty_date(n.gallery.created_at))}
      - unless 0 == n.gallery.photos.length
        .thumbnails
          - n.gallery.photos.where( :is_trash => false )[0...8].each do |photo|
            = link_to image_tag( photo.photo.url(:thumb), :alt => photo.name ), photo.photo.url(:small), :rel => "lightbox[#{n.gallery.slug}]"


    - if n.video_id
      - video = Video.unscoped.find n.video_id
      .a
        = link_to video.video.url, video.video.url
        -# %h3= link_to (video.name.blank? ? t('videos.no_title') : video.name), video_path(video.youtube_id)
        = render 'ish_manager/application/meta', :item => video
        = render 'ish_manager/videos/embed_half', :video => video
        .c

    - if !n.descr.blank? && n.gallery.blank? && n.report.blank?
      .Ndescr.panel
        .meta= pretty_date n.created_at
        .subhead= simple_format n.descr
        .c

app/views/ish_manager/newsitems/_show.haml
_item.haml

app/views/ish_manager/newsitems/edit.haml
.newsitems-edit.max-width
  %h1
    Edit Newsitem
  = render 'form', :newsitem => @newsitem

-# .debug= @newsitem.inspect

app/views/ish_manager/newsitems/index.haml
= render 'ish_manager/newsitems/index', newsitems: @newsitems

app/views/ish_manager/newsitems/new.haml
.newsitems-new.max-width
  %h1
    New Newsitem
  = render 'form', :newsitem => @newsitem